version: "3"

services:
  # 后端 API + Bot 核心
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nexus-core
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=file:../data/nexus.db
      - NAPCAT_URL=${NAPCAT_URL} # NapCat http api地址
      - NAPCAT_TOKEN=${NAPCAT_TOKEN}
      - BOT_QQ_ID=${BOT_QQ_ID}
      - XF_APPID=${XF_APPID}
      - XF_API_SECRET=${XF_API_SECRET}
      - XF_API_KEY=${XF_API_KEY}
      - NEXUS_PASSWORD=${NEXUS_PASSWORD} # Web 管理界面密码
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - nexus-network

#  # 前端 WebUI
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: nexus-web
#    ports:
#      - "80:80"
#    depends_on:
#      - backend
#    restart: unless-stopped
#    networks:
#      - nexus-network

networks:
  nexus-network:
    driver: bridge
